[build]
  command = "npm run build"
  publish = "dist"

[[edge_functions]]
  function = "og-preview"
  path = "/listing/*"

[[edge_functions]]
  function = "og-preview" 
  path = "/shop/*"

[build.environment]
  NODE_VERSION = "18"
