[[edge_functions]]
  function = "social-meta"
  path = "/listing/*"

[build]
  command = "npm run build"
  publish = "dist"

# Redirect social media bots for listing pages
[[redirects]]
  from = "/listing/:listingId"
  to = "/.netlify/functions/listing-meta?listingId=:listingId"
  status = 200
  conditions = {User-Agent = ["*bot*", "*crawler*", "*spider*", "*scraper*", "*preview*", "*facebook*", "*twitter*", "*whatsapp*", "*telegram*", "*discord*", "*slack*", "*linkedin*", "*pinterest*", "*facebookexternalhit*", "*twitterbot*"]}

# Redirect social media bots for shop pages
[[redirects]]
  from = "/shop/:shopUsername"
  to = "/.netlify/functions/shop-meta?shopUsername=:shopUsername"
  status = 200
  conditions = {User-Agent = ["*bot*", "*crawler*", "*spider*", "*scraper*", "*preview*", "*facebook*", "*twitter*", "*whatsapp*", "*telegram*", "*discord*", "*slack*", "*linkedin*", "*pinterest*", "*facebookexternalhit*", "*twitterbot*"]}

# Fallback for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
