[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  targetPort = 5173

[functions]
  node_bundler = "esbuild"

# Edge Function for listing page routing
[[edge_functions]]
  function = "listing-router"
  path = "/listing/*"

# Fallback for all other routes to SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
